config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :my_recipes, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :my_fermentables, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_hops, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_yeasts, only: [:index, :new, :create, :destroy, :update, :edit]
  end
  resources :recipes, only: [:index, :show]
  resource :search, only: [:show]
  resources :fermentables_measurements, only: [:create]
  resources :hops_measurements, only: [:create]
  resources :yeasts_measurements, only: [:create]
  resources :fermentables
  resources :hops
  resources :yeasts
  root to: 'recipes#index'
end

app/controllers/my_yeasts_controller.rb
class MyYeastsController < ApplicationController
  before_action :set_yeast, only: [:show, :edit, :update, :destroy]

  # GET /yeasts
  # GET /yeasts.json
  def index
    @yeasts = current_user.yeasts
  end

  # GET /yeasts/1/edit
  def edit
  end

  # GET /yeasts/1/edit
  def new
    @yeast = current_user.yeasts.new
  end

  # POST /yeasts
  # POST /yeasts.json
  def create
    @yeast = current_user.yeasts.new(yeast_params)

    respond_to do |format|
      if @yeast.save
        format.html { redirect_to user_my_yeasts_path(@yeast), notice: 'yeast was successfully created.' }
        format.json { render :show, status: :created, location: @yeast }
      else
        format.html { render :new }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yeasts/1
  # PATCH/PUT /yeasts/1.json
  def update
    respond_to do |format|
      if @yeast.update(yeast_params)
        format.html { redirect_to user_my_yeasts_path, notice: 'yeast was successfully updated.' }
        format.json { render :show, status: :ok, location: @yeast }
      else
        format.html { render :edit }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yeasts/1
  # DELETE /yeasts/1.json
  def destroy
    @yeast.destroy
    respond_to do |format|
      format.html { redirect_to yeasts_url, notice: 'yeast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yeast
      @yeast = yeast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yeast_params
      params.require(:yeast).permit(:name)
    end
end

app/views/my_yeasts/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editing Yeast</h1>

      <%= form_for(@yeast, url: user_my_yeast_path) do |f| %>
        <% if @yeast.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@yeast.errors.count, "error") %> prohibited this yeast from being saved:</h2>

            <ul>
            <% @yeast.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="small-4 columns">
            <%= f.label :name %>
          </div>
          <div class="small-8 columns">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.submit 'Save', class: 'button' %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/my_yeasts/index.html.erb
<div class="row">
  <div class="small-12 columns">

    <h1>Yeasts</h1>

    <%= link_to 'New yeast', new_user_my_yeast_path, class: 'button success' %>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @yeasts.each do |yeast| %>
          <tr>
            <td><%= yeast.name %></td>
            <td><%= link_to 'Edit', edit_user_my_yeast_path(current_user, yeast), class: 'button' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/my_yeasts/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>New Yeast</h1>

    <%= form_for(@yeast, url: user_my_yeasts_path) do |f| %>
      <% if @yeast.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@yeast.errors.count, "error") %> prohibited this yeast from being saved:</h2>

          <ul>
          <% @yeast.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
        <div class="small-4 columns">
          <%= f.label :name %>
        </div>
        <div class="small-8 columns">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 columns">
          <%= f.submit 'Create Yeast', class: 'button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/my_yeasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yeast.name %>
</p>