config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :my_recipes, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :my_fermentables, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_hops, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_yeasts, only: [:index, :new, :create, :destroy, :update, :edit]
  end
  resources :recipes, only: [:index, :show]
  resource :search, only: [:show]
  resources :fermentables_measurements, only: [:create]
  resources :hops_measurements, only: [:create]
  resources :yeasts_measurements, only: [:create]
  resources :fermentables
  resources :hops
  resources :yeasts
  root to: 'recipes#index'
end

app/models/hop.rb
class Hop < ApplicationRecord
  has_many :hops_measurements
  has_many :recipes, through: :hops_measurements
  belongs_to :user
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController
  before_action :set_hop, only: [:show, :edit, :update, :destroy]

  # GET /hops
  # GET /hops.json
  def index
    @hops = Hop.all
  end

  # GET /hops/1
  # GET /hops/1.json
  def show
  end

  # GET /hops/new
  def new
    @hop = Hop.new
  end

  # GET /hops/1/edit
  def edit
  end

  # POST /hops
  # POST /hops.json
  def create
    @hop = Hop.new(hop_params)

    respond_to do |format|
      if @hop.save
        format.html { redirect_to @hop, notice: 'Hop was successfully created.' }
        format.json { render :show, status: :created, location: @hop }
      else
        format.html { render :new }
        format.json { render json: @hop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hops/1
  # PATCH/PUT /hops/1.json
  def update
    respond_to do |format|
      if @hop.update(hop_params)
        format.html { redirect_to @hop, notice: 'Hop was successfully updated.' }
        format.json { render :show, status: :ok, location: @hop }
      else
        format.html { render :edit }
        format.json { render json: @hop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hops/1
  # DELETE /hops/1.json
  def destroy
    @hop.destroy
    respond_to do |format|
      format.html { redirect_to hops_url, notice: 'Hop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hop
      @hop = Hop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hop_params
      params.fetch(:hop, {})
    end
end

app/views/hops/_form.html.erb
<%= form_for(hop) do |f| %>
  <% if hop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hop.errors.count, "error") %> prohibited this hop from being saved:</h2>

      <ul>
      <% hop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hops/edit.html.erb
<h1>Editing Hop</h1>

<%= render 'form', hop: @hop %>

<%= link_to 'Show', @hop %> |
<%= link_to 'Back', hops_path %>

app/views/hops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hops</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hops.each do |hop| %>
      <tr>
        <td><%= link_to 'Show', hop %></td>
        <td><%= link_to 'Edit', edit_hop_path(hop) %></td>
        <td><%= link_to 'Destroy', hop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hop', new_hop_path %>

app/views/hops/new.html.erb
<h1>New Hop</h1>

<%= render 'form', hop: @hop %>

<%= link_to 'Back', hops_path %>

app/views/hops/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hop_path(@hop) %> |
<%= link_to 'Back', hops_path %>