config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :my_recipes, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :my_fermentables, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_hops, only: [:index, :new, :create, :destroy, :update, :edit]
    resources :my_yeasts, only: [:index, :new, :create, :destroy, :update, :edit]
  end
  resources :recipes, only: [:index, :show]
  resource :search, only: [:show]
  resources :fermentables_measurements, only: [:create]
  resources :hops_measurements, only: [:create]
  resources :yeasts_measurements, only: [:create]
  resources :fermentables
  resources :hops
  resources :yeasts
  root to: 'recipes#index'
end

app/controllers/fermentables_controller.rb
class FermentablesController < ApplicationController
  before_action :set_fermentable, only: [:show, :edit, :update, :destroy]

  # GET /fermentables
  # GET /fermentables.json
  def index
    @fermentables = Fermentable.all
  end

  # GET /fermentables/1
  # GET /fermentables/1.json
  def show
  end

  # GET /fermentables/new
  def new
    @fermentable = Fermentable.new
  end

  # GET /fermentables/1/edit
  def edit
  end

  # POST /fermentables
  # POST /fermentables.json
  def create
    @fermentable = Fermentable.new(fermentable_params)

    respond_to do |format|
      if @fermentable.save
        format.html { redirect_to @fermentable, notice: 'Fermentable was successfully created.' }
        format.json { render :show, status: :created, location: @fermentable }
      else
        format.html { render :new }
        format.json { render json: @fermentable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fermentables/1
  # PATCH/PUT /fermentables/1.json
  def update
    respond_to do |format|
      if @fermentable.update(fermentable_params)
        format.html { redirect_to @fermentable, notice: 'Fermentable was successfully updated.' }
        format.json { render :show, status: :ok, location: @fermentable }
      else
        format.html { render :edit }
        format.json { render json: @fermentable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fermentables/1
  # DELETE /fermentables/1.json
  def destroy
    @fermentable.destroy
    respond_to do |format|
      format.html { redirect_to fermentables_url, notice: 'Fermentable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fermentable
      @fermentable = Fermentable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fermentable_params
      params.fetch(:fermentable, {})
    end
end

app/views/fermentables/_form.html.erb
<%= form_for(fermentable) do |f| %>
  <% if fermentable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fermentable.errors.count, "error") %> prohibited this fermentable from being saved:</h2>

      <ul>
      <% fermentable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fermentables/edit.html.erb
<h1>Editing Fermentable</h1>

<%= render 'form', fermentable: @fermentable %>

<%= link_to 'Show', @fermentable %> |
<%= link_to 'Back', fermentables_path %>

app/views/fermentables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fermentables</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fermentables.each do |fermentable| %>
      <tr>
        <td><%= link_to 'Show', fermentable %></td>
        <td><%= link_to 'Edit', edit_fermentable_path(fermentable) %></td>
        <td><%= link_to 'Destroy', fermentable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fermentable', new_fermentable_path %>

app/views/fermentables/new.html.erb
<h1>New Fermentable</h1>

<%= render 'form', fermentable: @fermentable %>

<%= link_to 'Back', fermentables_path %>

app/views/fermentables/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fermentable_path(@fermentable) %> |
<%= link_to 'Back', fermentables_path %>